### PR TITLE
update benchmarks to include HiGHS solver

### PR DESCRIPTION
**Pull request by jeffreyhanson**
I've updated the benchmarks repository to include the HiGHS solver. To acheive this, it uses developmental versions of the highs and prioritizr R packages for analysis (discussed in https://github.com/prioritizr/prioritizr/issues/250). I have also updated the package management system to use renv, and updated the dependencies so they are compatible with R version 4.2.1. I have also updated  the code so that it won't overwrite the current "latest" benchmarks. @ricschuster, when you get a chance, could you please try re-running the benchmarks with this branch?

### CODE REVIEW

**Comment by jeffreyhanson** [comment]
@ricschuster, I think I've got it working now. Could you please try running the benchmarks on your system?

**Comment by ricschuster** [comment]
Setup is working and debug mode completed. Now switching over to release mode. 
Exciting!

**Comment by ricschuster** [comment]
Dang. 3 days in and I get this for `benchmark_results_part_1` after 340 scenarios completed:

```
Error in unserialize(socklist[[n]]) : error reading from connection
Calls: %>% ... recvOneData -> recvOneData.SOCKcluster -> unserialize
In addition: Warning messages:
1: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
 
2: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
 
Execution halted
```

Sounds like not straight forward to troubleshoot.
@jeffreyhanson  any ideas?

One related thing that I think we have discussed before was whether we can save `benchmark_results` out in the loop to not loose all progress if we get an error. What do you think?

**Comment by jeffreyhanson** [comment]
Ah that's annoying - yeah, IIRC we did put in some caching logic (e.g. see https://github.com/prioritizr/benchmark/blob/main/code/R/analysis/03-analysis.R#L121-L136)? There should be a `data/intermediate/runs` and `data/intermediate/solutions` folder that contains the results of the succesful runs, and the previous results should be automatically loaded in when performing a subsequent run. So, if you run `make analysis` again, then it should basically continue where it left off? Note that if you run `make clean` then this will delete the previous runs - so I wouldn't recommend doing that.

**Comment by ricschuster** [comment]
That's great! Thanks very much Jeff! I'm just going to restart and see if it continues or throws the error again.

**Comment by ricschuster** [comment]
I got the error again. `03-analysis.Rout` is here:
[03-analysis.zip](https://github.com/prioritizr/benchmark/files/9556951/03-analysis.zip)

Do you know whether the sequence of runs goes from row 1 to nrows(x)? If so, it threw an error with 340 runs complete/saved. It ran for about 48h before the error came up.

Any ideas?

To get some results for HiGHS I could remove rsymphony and lpsymphony and try again.

**Comment by jeffreyhanson** [comment]
Hmm, just to check, when you set up the dependencies, did you use `make install`? This is important so the `code/R/scripts/init.R`  script is used to install the dev version of highs (not the CRAN one).

**Comment by ricschuster** [comment]
Yes I used `make install`.

**Comment by jeffreyhanson** [comment]
Ah ok, I could have a go at trying to make the caching a bit cleverer. I'll see what I can do.

**Comment by ricschuster** [comment]
Thanks Jeff!

**Comment by jeffreyhanson** [comment]
Ok - I've just pushed a commit which should help reduce failures. Can you pull the changes and start it running again with `make analysis`? You shouldn't need to reinstall the dependencies or start again from scratch.

**Comment by ricschuster** [comment]
Thanks very much Jeff!
I'm currently testing with `add_highs_solver` alone to see whether that causes the issue.

**Comment by ricschuster** [comment]
Is there a way to switch `MODE` without needing to re-run 00* - 02*?

**Comment by jeffreyhanson** [comment]
Yeah, the new highs solver is probably what's causing problems. Nah, you can't change MODE mid-way through (it's set right at the start of the analysis). To help debug it, I would suggest the following

1. Manually hard-code the analysis to only do one run at a time (in other words, disable parallel processing). To do this, insert this code at this line (https://github.com/prioritizr/benchmark/blob/main/code/R/analysis/03-analysis.R#L9): `general_parameters$threads <- 1L`.
2. This will now cause the code to print the run numbers to the log files when it processes them (i.e. id column value in `benchmark_results`) (see https://github.com/prioritizr/benchmark/blob/highs-solver/code/R/analysis/03-analysis.R#L146).
3. Next time it cashes, you can identify which run number is causing issues because it will be the last id in the log file. Note that this hopefully won't take too long because you'll be using the cached results from previous runs.
4. Once you've worked out which run id is causing the problem, try running these lines (https://github.com/prioritizr/benchmark/blob/highs-solver/code/R/analysis/03-analysis.R#L146) to generate the `benchmark_reuslts` data (which at this point will only contain the parameters used for the runs, not any actual results yet) and then filter it to find the run which is causing issues.

How does that sound? Does that help?

**Comment by ricschuster** [comment]
Thanks Jeff! That's very helpful. I've currently the highs solver running on its own and its working so far. Once things crash I will used the suggestions you have posted.

**Comment by ricschuster** [comment]
It hasn't failed yet, but as the following scenario has been running for 12h I thought I'd post the specs here.
I have followed the steps you outlined above and that's how I got the `id`. Having a look at the problem puzzles me as to why this is taking so long. The problem is 100k pu's, min shortfall and a small boundary penalty. Do you have an idea as to why this might be taking so long?

image

**Comment by jeffreyhanson** [comment]
Hmm, maybe HiGHS isn't good at a min shortfall problems? Not sure. The limit specified is 1e+8 seconds - which is a couple of thousand hours -- so I guess the code is behaving within specified parameters. Maybe it's worth dropping the time limit to 6 hours or something?
________________________________

**Comment by ricschuster** [comment]
That's a good idea with the time limit. Do you currently have something in the code that would flag that the time limit has been reached? If not, that might be good so we can flag runs that didn't complete within the time limit.

**Comment by jeffreyhanson** [comment]
Yeah, this info should be in the `exceeded_run_time` column (see https://github.com/prioritizr/benchmark/blob/main/code/R/analysis/03-analysis.R#L223).

**Comment by ricschuster** [comment]
Perfect! I will start things again with a 6h time limit.

**Comment by jeffreyhanson** [comment]
Ok awesome - thanks!

**Comment by jeffreyhanson** [comment]
An updated version of this branch has been merged to the main branch, so closing this PR

**Pull request closed without merging**
